/*---------------------------------------------------------
  The options statement below should be placed
  before the data step when submitting this code.
---------------------------------------------------------*/
options VALIDMEMNAME=EXTEND VALIDVARNAME=ANY;
   /*------------------------------------------
   Generated SAS Scoring Code
     Date             : 10Oct2022:00:15:05
     Locale           : en_US
     Model Type       : Decision Tree
     Interval variable: Order Quantity
     Class variable   : Order Priority
     Class variable   : Product Category
     Class variable   : Product Container
     Class variable   : Product Sub-Category
     Class variable   : Reached on Time
     Response variable: Reached on Time
     ------------------------------------------*/
   /*---------------------------------------------------------
   SAS Code Generated by Cloud Analytic Services for Decision Tree
     Date                  : 10Oct2022:04:15:05 UTC
     Number of Nodes       : 17
     Number of Tree Depth  : 6
     Number of Bins        : 50
     Number of Obs         : 2520
     -------------------------------------------------------*/

   length _strfmt_ $30; drop _strfmt_;
   _strfmt_ = ' ';

   array _tlevname_5622_{2} $32 _temporary_ ( '                               0' 
   '                               1');

   array _dt_fi_5622_{2} _temporary_;

   _node_id_ =  0;
   _new_id_  = -1;
   nextnode_5622:
   if _node_id_ eq 0 then do;
         _strfmt_ = left(trim(put('Order Priority'n,$13.)));
         if _strfmt_ in ('High',
         'Low',
         'Critical') then do;

         _new_id_ = 1;
         end;
         else if _strfmt_ in ('Medium',
         'Not Specified') then do;

         _new_id_ = 2;
         end;
         else do;
         _new_id_ = 1;
         end;
   end;
   else if _node_id_ eq 1 then do;
         _leaf_id_ = 1;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.63891201776297;
         _dt_fi_5622_{1} =     0.63891201776297; 
         _dt_fi_5622_{2} =     0.36108798223702; 
   end;
   else if _node_id_ eq 2 then do;
         _numval_ = 'Order Quantity'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 9 and _numval_ lt 50) then do;

            _new_id_ = 3;
         end;
         else if (_numval_ ge 1 and _numval_ lt 9) then do;

            _new_id_ = 4;
         end;
         else if (_numval_ lt 1) then do;
            _new_id_ = 4;
         end;
         else if (_numval_ ge 50) then do;
            _new_id_ = 3;
         end;
         else do;
         _new_id_ = 3;
         end;
   end;
   else if _node_id_ eq 3 then do;
         _strfmt_ = left(trim(put('Product Container'n,$10.)));
         if _strfmt_ in ('Wrap Bag',
         'Medium Box',
         'Jumbo Drum',
         'Small Box') then do;

         _new_id_ = 5;
         end;
         else if _strfmt_ in ('Large Box',
         'Jumbo Box',
         'Small Pack') then do;

         _new_id_ = 6;
         end;
         else do;
         _new_id_ = 5;
         end;
   end;
   else if _node_id_ eq 4 then do;
         _strfmt_ = left(trim(put('Product Category'n,$15.)));
         if _strfmt_ in ('Furniture',
         'Office Supplies') then do;

         _new_id_ = 7;
         end;
         else if _strfmt_ in ('Technology') then do;

         _new_id_ = 8;
         end;
         else do;
         _new_id_ = 7;
         end;
   end;
   else if _node_id_ eq 5 then do;
         _leaf_id_ = 5;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.66959459459459;
         _dt_fi_5622_{1} =     0.66959459459459; 
         _dt_fi_5622_{2} =      0.3304054054054; 
   end;
   else if _node_id_ eq 6 then do;
         _strfmt_ = left(trim(put('Product Sub-Category'n,$30.)));
         if _strfmt_ in ('Office Furnishings',
         'Computer Peripherals',
         'Scissors, Rulers and Trimmers',
         'Chairs & Chairmats',
         'Appliances',
         'Pens & Art Supplies',
         'Storage & Organization',
         'Tables',
         'Telephones and Communication',
         'Bookcases') then do;

         _new_id_ = 9;
         end;
         else if _strfmt_ in ('Office Machines',
         'Copiers and Fax') then do;

         _new_id_ = 10;
         end;
         else do;
         _new_id_ = 9;
         end;
   end;
   else if _node_id_ eq 7 then do;
         _strfmt_ = left(trim(put('Product Sub-Category'n,$30.)));
         if _strfmt_ in ('Office Furnishings',
         'Chairs & Chairmats',
         'Appliances',
         'Pens & Art Supplies',
         'Binders and Binder Accessories',
         'Labels',
         'Tables') then do;

         _new_id_ = 11;
         end;
         else if _strfmt_ in ('Envelopes',
         'Rubber Bands',
         'Scissors, Rulers and Trimmers',
         'Paper',
         'Storage & Organization',
         'Bookcases') then do;

         _new_id_ = 12;
         end;
         else do;
         _new_id_ = 11;
         end;
   end;
   else if _node_id_ eq 8 then do;
         _leaf_id_ = 8;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.71134020618556;
         _dt_fi_5622_{1} =     0.71134020618556; 
         _dt_fi_5622_{2} =     0.28865979381443; 
   end;
   else if _node_id_ eq 9 then do;
         _leaf_id_ = 9;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.75202156334231;
         _dt_fi_5622_{1} =     0.75202156334231; 
         _dt_fi_5622_{2} =     0.24797843665768; 
   end;
   else if _node_id_ eq 10 then do;
         _numval_ = 'Order Quantity'n;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 38 and _numval_ lt 50) then do;

            _new_id_ = 13;
         end;
         else if (_numval_ ge 1 and _numval_ lt 38) then do;

            _new_id_ = 14;
         end;
         else if (_numval_ lt 1) then do;
            _new_id_ = 14;
         end;
         else if (_numval_ ge 50) then do;
            _new_id_ = 13;
         end;
         else do;
         _new_id_ = 14;
         end;
   end;
   else if _node_id_ eq 11 then do;
         _strfmt_ = left(trim(put('Order Priority'n,$13.)));
         if _strfmt_ in ('Not Specified') then do;

         _new_id_ = 15;
         end;
         else if _strfmt_ in ('Medium') then do;

         _new_id_ = 16;
         end;
         else do;
         _new_id_ = 15;
         end;
   end;
   else if _node_id_ eq 12 then do;
         _leaf_id_ = 12;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.72093023255813;
         _dt_fi_5622_{1} =     0.72093023255813; 
         _dt_fi_5622_{2} =     0.27906976744186; 
   end;
   else if _node_id_ eq 13 then do;
         _leaf_id_ = 13;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =                 0.75;
         _dt_fi_5622_{1} =                 0.25; 
         _dt_fi_5622_{2} =                 0.75; 
   end;
   else if _node_id_ eq 14 then do;
         _leaf_id_ = 14;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.64285714285714;
         _dt_fi_5622_{1} =     0.64285714285714; 
         _dt_fi_5622_{2} =     0.35714285714285; 
   end;
   else if _node_id_ eq 15 then do;
         _leaf_id_ = 15;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.59340659340659;
         _dt_fi_5622_{1} =     0.59340659340659; 
         _dt_fi_5622_{2} =      0.4065934065934; 
   end;
   else if _node_id_ eq 16 then do;
         _leaf_id_ = 16;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =     0.56097560975609;
         _dt_fi_5622_{1} =      0.4390243902439; 
         _dt_fi_5622_{2} =     0.56097560975609; 
   end;
   if _new_id_ >= 0 then do;
       _node_id_ = _new_id_;
      goto nextnode_5622;
   end;

   I_Reached_on_Time = _tlevname_5622_{_dt_pred_lev_+1};
   label I_Reached_on_Time = 'Into: Reached on Time';
   _i_ = 1;
   _dt_predp_ = _dt_fi_5622_{_i_};
   P_Reached_on_Time0 = _dt_predp_;
   label P_Reached_on_Time0 = 'Predicted: Reached on Time=0';
   _i_+1;
   _dt_predp_ = _dt_fi_5622_{_i_};
   P_Reached_on_Time1 = _dt_predp_;
   label P_Reached_on_Time1 = 'Predicted: Reached on Time=1';
   _i_+1;
   drop _dt_predp_;
   drop _i_;
   drop _dt_pred_lev_;
   drop _dt_pred_prob_;
   drop _numval_;
   drop _node_id_;
   drop _new_id_;
   /*------------------------------------------*/
   /*_VA_DROP*/ drop 'I_Reached_on_Time'n '_leaf_id_'n 'P_Reached_on_Time0'n 'P_Reached_on_Time1'n;
length 'I_Reached_on_Time_5622_2'n $32;
      'I_Reached_on_Time_5622_2'n='I_Reached_on_Time'n;
'P_Reached_on_Time0_5622_2'n='P_Reached_on_Time0'n;
'P_Reached_on_Time1_5622_2'n='P_Reached_on_Time1'n;
'_leaf_id__5622_2'n='_leaf_id_'n;
   /*------------------------------------------*/